# Generated by Django 4.2.10 on 2024-03-10 08:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exptrack", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="income",
            options={},
        ),
        migrations.AlterField(
            model_name="income",
            name="date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
